export const LOAD: 'LOAD' = 'LOAD'
export const TYPE_ERROR: 'TYPE_ERROR' = 'TYPE_ERROR'
export const UNKNOWN_ERROR: 'UNKNOWN_ERROR' = 'UNKNOWN_ERROR'
export const HIDE_ALERT = 'HIDE_ALERT'
export const ADD_PARAMS = 'ADD_PARAMS'
export const SHOW_LOADER = 'SHOW_LOADER'
export const REMOVE_FILE = 'REMOVE_FILE'